version: "3.8"
services:
  broker:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=broker
  order-service:
    image: order-service:v1
    ports:
      - "8080"
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  payment-service:
    image: payment-service:v1
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  stock-service:
    image: stock-service:v1
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
